require("dotenv").config();

const express = require("express");
const cors = require("cors");
const fs = require("fs");
const path = require("path");

const app = express();

app.use(cors());
app.use(express.json({ limit: "15mb" }));

const PORT = 5000;
app.post("/api/generate-quiz", async (req, res) => {
    try {
        const { topic, difficulty } = req.body;

        if (!topic || typeof topic !== "string") {
            return res.status(400).json({
                message: "Please select a topic"
            });
        }

        const response = await fetch(
            "https://router.huggingface.co/v1/chat/completions",
            {
                method: "POST",
                headers: {
                    Authorization: `Bearer ${process.env.HF_TOKEN}`,
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    model: "meta-llama/Llama-3.1-8B-Instruct:fastest",
                    messages: [
                        {
                            role: "system",
                            content: `Generate exactly 10 multiple choice quiz questions.
Return ONLY valid JSON in this format:
{
 "questions": [
  {
   "question": "Question text",
   "options": ["A", "B", "C", "D"],
   "answer": 0
  }
 ]
}
The answer must be the zero-based index of the correct option.
No markdown or extra text.`
                        },
                        {
                            role: "user",
                            content: `Generate 10 unique ${difficulty || "medium"} difficulty MCQ questions about ${topic}. Use different questions each time.`
                        }
                    ],
                    temperature: 0.9,
                    max_tokens: 1800
                })
            }
        );

        const data = await response.json();

       if (!response.ok) {
            return res.status(response.status).json({
                 message: data.error || "AI generation failed"
            });
        }

        const content = data.choices?.[0]?.message?.content;

        const cleanContent = content
            .replace(/```json/gi, "")
            .replace(/```/g, "")
            .trim();

        const quiz = JSON.parse(cleanContent);

if (
    !Array.isArray(quiz.questions) ||
    quiz.questions.length < 1 ||
    quiz.questions.some(q =>
        typeof q.question !== "string" ||
        !Array.isArray(q.options) ||
        q.options.length !== 4 ||
        !Number.isInteger(q.answer) ||
        q.answer < 0 ||
        q.answer > 3
    )
) {
    console.log("AI RAW RESPONSE:", JSON.stringify(data, null, 2));
    console.log("PARSED QUIZ:", JSON.stringify(quiz, null, 2));

    throw new Error("Invalid quiz format generated by AI");
}

        res.json(quiz);

    } catch (error) {
        console.error(error);

        res.status(500).json({
            message: "Unable to generate quiz",
            error: error.message
        });
    }
});
app.listen(PORT, () => {
    console.log(`QuizMaster server running on http://localhost:${PORT}`);
});